# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: docs/readthedocs-pip-requirements.txt

sphinx:
  configuration: docs/source/conf.py

