name: Python package

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:      
      matrix:
        os: [ubuntu-latest, macos-14]
        build_type: [Release]
        c_compiler: [clang]
        python-version: ["3.12"]
        include:
          - os: ubuntu-latest
            apt: 10
          - os: macos-14
            brew: 20
          - os: windows-latest
            powershell: 30
    steps:
    - uses: actions/checkout@v2
    - if: ${{ matrix.apt }}
      run: sudo apt-get install libhdf5-dev libgsl0-dev
    - if: ${{ matrix.brew }}
      run: |
        brew install gsl
        brew install hdf5      
    - name: Set up Python ${{ matrix.python-version }}
      shell: bash
      run: |
        "${SHELL}" <(curl -L micro.mamba.pm/install.sh)
        micromamba self-update
        micromamba create -n moose python=${{ matrix.python-version }} graphviz lxml cmake numpy matplotlib vpython hdf5 pytables doxygen -c conda-forge
        eval "$(micromamba shell hook --shell bash)"
        micromamba activate moose
        pip install python-libsbml
        pip install pyneuroml
    - name: Build
      run: |
        pip install .
         
  winbuild:
    name: Windows-build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      shell: pwsh
      run: |
        Invoke-Expression ((Invoke-WebRequest -Uri https://micro.mamba.pm/install.ps1).Content)
        micromamba shell init -s powershell -p C:\Users\runneradmin\micromamba
        micromamba self-update
        micromamba create -n moose python=${{ matrix.python-version }} graphviz lxml cmake numpy matplotlib vpython hdf5 gsl pytables doxygen -c conda-forge
        micromamba activate moose
        pip install python-libsbml
        pip install pyneuroml
    - name: Build
      run: |
        pip install .
      
    
