name: Python package

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:      
      matrix:
        os: [ubuntu-latest, macos-14]
        build_type: [Release]
        c_compiler: [clang]
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      shell: bash
      run: |
        "${SHELL}" <(curl -L micro.mamba.pm/install.sh)
        micromamba self-update
        micromamba create -n moose cmake numpy matplotlib vpython hdf5 doxygen gsl python=${{ matrix.python-version }} -c conda-forge
        eval "$(micromamba shell hook --shell bash)"
        micromamba activate moose
        pip install python-libsbml
        pip install pyneuroml
    - name: Build
      run: |
        pip install .
         
