name: Python package

on: [push]

jobs:
  build:
    strategy:      
      matrix:
        os: [ubuntu-latest, macos-14]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v1
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install micromamba
          run: |
            "${SHELL}" <(curl -L micro.mamba.pm/install.sh)
            micromamba self-update
            micromamba create -n moose cmake numpy matplotlib vpython python3-tk libhdf5 doxygen gsl 
            micromamba activate moose
            pip install python-libsbml
        - name: Build
          run: |
            pip install .
         
