name: Python package

on: [push]

jobs:
  win-build:
    runs-on: windows-latest
    strategy:      
      matrix:
        os: [windows-latest]
        build_type: [Release]
        python-version: ["3.12"]
    steps:
      - name: InstallMicromamba
        shell: pwsh
        run: |
          Invoke-Expression ((Invoke-WebRequest -Uri https://micro.mamba.pm/install.ps1).Content)
          C:\Users\runneradmin\AppData\Local\micromamba\micromamba.exe shell init -s powershell
          micromamba -y self-update
          micromamba create -n moose python=${{ matrix.python-version }} graphviz lxml cmake numpy matplotlib vpython hdf5 gsl pytables doxygen -c conda-forge -y
          micromamba activate moose
          micromamba install gsl -c conda-forge -y
          gsl-config --cflags
          # pip install python-libsbml
          # pip install pyneuroml
          pip install .
        
    # - name: Build
    #   run: |
    #     pip install .
      
    
