name: Python package

on: [push]

jobs:
  # build:
  #   runs-on: ${{ matrix.os }}
    
  #   strategy:      
  #     matrix:
  #       os: [ubuntu-latest, macos-14]
  #       build_type: [Release]
  #       c_compiler: [clang]
  #       python-version: ["3.12"]
  #       include:
  #         - os: ubuntu-latest
  #           apt: 10
  #         - os: macos-14
  #           brew: 20
  #   steps:
  #   - uses: actions/checkout@v2
  #   - if: ${{ matrix.apt }}
  #     run: sudo apt-get install libhdf5-dev libgsl0-dev
  #   - if: ${{ matrix.brew }}
  #     run: |
  #       brew install gsl
  #       brew install hdf5      
  #   - name: Set up Python ${{ matrix.python-version }}
  #     shell: bash
  #     run: |
  #       "${SHELL}" <(curl -L micro.mamba.pm/install.sh)
  #       micromamba self-update
  #       micromamba create -n moose python=${{ matrix.python-version }} graphviz lxml cmake numpy matplotlib vpython hdf5 pytables doxygen -c conda-forge
  #       eval "$(micromamba shell hook --shell bash)"
  #       micromamba activate moose
  #       pip install python-libsbml
  #       pip install pyneuroml
  #   - name: Build
  #     run: |
  #       pip install .
         
  winbuild:
    name: Windows-build
    runs-on: windows-latest
    strategy:      
      matrix:
        os: [windows-latest]
        build_type: [Release]
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v2
    # - name: Set up Python ${{ matrix.python-version }}
    #   shell: pwsh
    #   # NOTE: hard-coded default micromamba.exe path 
    #   run: |
    #     Invoke-Expression ((Invoke-WebRequest -Uri https://micro.mamba.pm/install.ps1).Content)
    #     C:\Users\runneradmin\AppData\Local\micromamba\micromamba.exe shell init -s powershell -p C:\Users\runneradmin\micromamba
    #     C:\Users\runneradmin\AppData\Local\micromamba\micromamba.exe shell reinit --shell powershell
    #     C:\Users\runneradmin\AppData\Local\micromamba\micromamba.exe -y self-update
    #     C:\Users\runneradmin\AppData\Local\micromamba\micromamba.exe create -n moose python=${{ matrix.python-version }} graphviz lxml cmake numpy matplotlib vpython hdf5 gsl pytables doxygen -c conda-forge -y
    #     C:\Users\runneradmin\AppData\Local\micromamba\micromamba.exe activate moose
    #     pip install python-libsbml
    #     pip install pyneuroml
    - name: BuildGSL
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://github.com/ampl/gsl/archive/refs/tags/20211111.zip -Outfile .\20211111.zip
        unzip 20211111.zip
        cd gsl-20211111
        mkdir build
        cmake .. -G"Unix Makefiles" -DNO_AMPL_BINDINGS=1 -DGSL_DISABLE_TESTS=1 -DDOCUMENTATION=OFF GSL_INSTALL_MULTI_CONFIG=ON
        make .
        ls -l
        
    # - name: Build
    #   run: |
    #     pip install .
      
    
